spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8000          
management:
  endpoints:
    web:
      exposure:
        include: '*'
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    registry-fetch-interval-seconds: 2
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
